# -*- coding: utf-8 -*-
"""DE_jul_17_2019.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q-M5N8NgxuvSVsZOS0efaSQXqTurqi_6
"""

import numpy as np

'''https://pablormier.github.io/2017/09/05/a-tutorial-on-differential-evolution-with-python/'''

def Fun( sol):
  #Schwefel(x):
  x=sol  
  summ=0
  for i in range(len(x)):
    new=x[i]*np.sin((abs(x[i]))**0.5)
    summ=summ+new
    top=(418.9829*len(x)-summ) 
  
  return top;

def DE(MAX,MIN, mut, crossp, popsize, its,fobj):
    
  Num=len(MAX)
  bounds=[(0,0)] * Num
  for i in range(Num):
    bounds[i]=(MIN[i], MAX[i])
   

  dimensions = len(bounds)
  
  pop = np.random.rand(popsize, dimensions)
  min_b, max_b = np.asarray(bounds).T
  diff = np.fabs(min_b - max_b)
  pop_denorm = min_b + pop * diff
  fitness = np.asarray([fobj(ind) for ind in pop_denorm])
  best_idx = np.argmin(fitness)
  best = pop_denorm[best_idx]
  for i in range(its):
    for j in range(popsize):
      idxs = [idx for idx in range(popsize) if idx != j]
      a, b, c = pop[np.random.choice(idxs, 3, replace = False)]
      mutant = np.clip(a + mut * (b - c), 0, 1)
      cross_points = np.random.rand(dimensions) < crossp
      if not np.any(cross_points):
        cross_points[np.random.randint(0, dimensions)] = True
      trial = np.where(cross_points, mutant, pop[j])
      trial_denorm = min_b + trial * diff
      f = fobj(trial_denorm)
      if f < fitness[j]:
        fitness[j] = f
        pop[j] = trial
        if f < fitness[best_idx]:
          best_idx = j
          best = trial
          
    pop_denorm = min_b + pop * diff
    fitness = np.asarray([fobj(ind) for ind in pop_denorm])

  fitness = np.asarray([fobj(ind) for ind in pop_denorm])
  best_idx = np.argmin(fitness)
  best = pop_denorm[best_idx]
  fobj_best = fitness[best_idx]

  x=pop
  y=fitness

  BEST=best
  FOBEST=fobj_best
  XY= np.c_[x,y] #concatena x e y em 2 colunas            
  XYsorted = XY[XY[:,-1].argsort()] #Ordena a partir da last col(Y) for all row
  XY=XYsorted
  BEST_XY =np.append(BEST,FOBEST)
  
  return BEST,FOBEST,XY,BEST_XY

'''

MAX=[500,500,500] # MAXIMO DE CADA PARAMETRO
MIN=[-500,-500,-500] # MINIMO DE CADA PARAMETRO
mut=0.8
crossp=0.7
NPAR=100
ITE=100

runtime=1

for run in range(runtime):
  BEST,FOBEST,XY,BEST_XY= de(MAX,MIN, mut, crossp, NPAR, ITE,Fun)     
  print("GlobalParam e Solucao:", BEST_XY)

mean=np.average(FOBEST)


print("Means of",runtime,"runs:",mean,"\n")

'''
